books_authors_app0/urls.py
from django.urls import path

from . import views

app_name = 'books_authors_app0'  # Add this line to specify the app name

urlpatterns = [
    path('', views.books, name='books'),
    path('books/<int:pk>',views.book_details, name='details'),
    path('books/add/<int:pk>',views.add_author_to_book, name='add_book'),
    path('authors', views.authors, name='authors'),
    path('author_details/<int:pk>',views.author_details, name='author_details'),
    path('author/add/<int:pk>',views.add_book_to_author, name='add_author')

]

books_authors_proj0/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books_authors_app0.urls', namespace='books_authors_app0')),    ]

books_authors_app0/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    note = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    authors = models.ManyToManyField(Author)

    def __str__(self):
        return self.title

books_authors_app0/forms.py
from django import forms

from .models import Book , Author


class BookForm(forms.ModelForm):
    class Meta:
        model= Book 
        fields = ["title", "description"]

    
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'


class AuthorForm(forms.ModelForm):
    class Meta:
        model= Author 
        fields = ["first_name", "last_name","note"]

    
    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['note'].widget.attrs['class'] = 'form-control'

books_authors_app0/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Book, Author
from .forms import BookForm , AuthorForm


def books(request):
    books = Book.objects.all()
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_authors_app0:books')

    context = {
        'books': books,
         'form': form
    }
    return render(request, 'books.html', context)


def book_details(request, pk):
    
    #book = Book.objects.get(id=pk)
    book = get_object_or_404(Book, id=pk)
    book_authors = book.authors.all()
    authors = Author.objects.all()

    context = {'book': book, 'book_authors': book_authors, 'authors': authors}
    return render(request, "book_details.html", context)


def add_author_to_book(request, pk):
    book = Book.objects.get(id=pk)
    author_id = request.POST['bbb']
    author = Author.objects.get(id=author_id)
    book.authors.add(author)
    book.save()

    return redirect('books_authors_app0:details', pk=pk)




def authors(request):
    author = Author.objects.all()
    form = AuthorForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_authors_app0:authors')
    
    context = {
        'author': author,
        'form': form
    }

    return render(request, 'authors.html', context)


def author_details(request, pk):

    author = Author.objects.get(id=pk)
    books_authors = author.book_set.all()
    books = Book.objects.all()

    context = {
        'books_of_author': books_authors,
        'author': author,
        'books': books
        }
    
    return render(request, "author_details.html", context)


def add_book_to_author(request, pk):
    author = Author.objects.get(id=pk)
    book_id = request.POST['bbb']
    book = Book.objects.get(id=book_id)
    book.authors.add(author)
    book.save()
    
    return redirect('books_authors_app0:author_details', pk=pk)

templates/author_details.html
{% extends './base.html' %}
{% block content %}
        <div class="row mt-5">
            <h1 class="mb-5">{{author.first_name}} {{author.last_name}} </h1>
            <div>
                <span class="bold">ID</span>: {{author.id}} <br> <br>
                <span >Notes:</span> {{author.note}}  <br><br>
                <div >
                    <p>Books:</p>
                    <ul>
                        {% for book in books_of_author %}
                        <li >
                            {{book.title}}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <br>
                <form method="POST" action="{% url 'books_authors_app0:add_author' pk=author.id %}"> 
                    {% csrf_token %}
                    <div style="max-width: 250px">
                    <select  name="bbb" class="form-select">
                        {% for book in books %}
                        <option value={{book.id}}>{{book}}</option>
                        {% endfor %}
                        
                    </select>
                    </div>
                <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>
{% endblock content %}

templates/authors.html
{% extends './base.html' %}
{% block content %}
        <div class="row mt-5">
            <div class="col-6">
                <h1 class="mb-5">Add Author</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label class="form-label">First Name</label>
                      {{form.first_name}}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Last Name</label>
                          {{form.last_name}}
                      </div>
                    <div class="mb-3">
                      <label class="form-label">Note</label>
                        {{form.note}}
                    </div>
                
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
            <div class="col-6 p-3">
                <table class="table p-5">
                    <thead>
                      <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for author in author %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td scope="col">{{author.first_name}}</td>
                        <td><a href="{% url 'books_authors_app0:author_details' pk=author.id %}" class="btn btn-link">View</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books - Authors</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="\">Books Authors</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'books_authors_app0:books'%}">Books</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'books_authors_app0:authors'%}">Authors</a>
              </li>
              
            </ul>
           
          </div>
        </div>
      </nav>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

templates/book_details.html
{% extends './base.html' %}
{% block content %}
        <div class="row mt-5">
            <h1 class="mb-5">{{book.title}}</h1>
            <div>
                <span class="bold">ID</span>: {{book.id}} <br> <br>
                <span >Description</span>: {{book.description}}  <br><br>
                <div >
                    <p>Authors:</p>
                    <ul>
                        {% for author in book_authors %}
                        <li >
                          {{author.first_name}} {{author.last_name}}
                        </li>
                        {% endfor %}
                      </ul>
                     
                </div>
                <br>
                <form method="POST" action="{% url 'books_authors_app0:add_book' pk=book.id %}"> 
                    {% csrf_token %}
                    <div style="max-width: 250px">
                    <select  name="bbb" class="form-select"  >
                        <option selected>Select a author</option>
                        {% for author in authors %}
                        <option value={{author.id}}>{{author}}</option>
                        {% endfor %}
                        
                    </select>
                    </div>
                <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>
{% endblock content %}

templates/books.html
{% extends './base.html' %}
{% block content %}
        <div class="row mt-5">
            <div class="col-6">
                <h1 class="mb-5">Add a Book</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label class="form-label">Title</label>
                      {{form.title}}
                    </div>
                    <div class="mb-3">
                      <label class="form-label">Description</label>
                        {{form.description}}
                    </div>
                   
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
            <div class="col-6 p-3">
                <table class="table p-5">
                    <thead>
                      <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td scope="col">{{book.title}}</td>
                        <td><a href="{% url 'books_authors_app0:details' pk=book.id %}" class="btn btn-link">View</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
{% endblock content %}